### ISSUE TITLE
How to change the binding IP and Port?

### ISSUE THREAD

**Issue by liangxin1300** [hawk-ui/hawk-web-client#18]
Hi ayoub:
    
How to change the binding IP and Port? I want start it at 0.0.0.0:otherPort
And, do I still need install hawk2 and hawk-apiserver?

Thanks!
Regards,
xin

**Comment by ayoub-belarbi** [comment]
Hi Xin :)
In order to change the port number, you have to manually change it [here](https://github.com/hawk-ui/hawk-web-client/blob/2ee3e41e5d9f43d3bd6a33c97d08455f077f4bfb/config/index.js#L26)

For the Binding ip, Change the host string from 'http://localhost:' to 'http://0.0.0.0:' [here](https://github.com/hawk-ui/hawk-web-client/blob/2ee3e41e5d9f43d3bd6a33c97d08455f077f4bfb/build/dev-server.js#L67)

Then, start the server normally using yarn or npm (yarn run dev) and it should work.

The client now is not using the hawk api, since the latter is not finished, we have a dummy api server that you can run in parallel (yarn run api), so the client can fetch some data.

regards,
Ayoub

**Comment by ayoub-belarbi** [comment]
Going to close this issue now :) Thanks
